---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-demo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: staging-project
  source:
    repoURL: http://gitea-http.gitea.svc:3000/simple-gitops-poc/staging-cluster.git
    targetRevision: main  
    path: manifests/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3