---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  labels: { app: todolist-service }
spec:
  replicas: 1
  selector:
    matchLabels: { app: todolist-service }
  template:
    metadata:
      labels: { app: todolist-service }
    spec:
      containers:
        - name: app
          image: YOUR_REGISTRY/todolist-service:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef: { name: todolist-config }
            - secretRef:    { name: todolist-secrets }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }