---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: act-runner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: shared-infra
  source:
    repoURL: http://<HOST(SVC|FQDN|etc..)>/<REPOGIT>.git
    targetRevision: main  
    path: manifests/act-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-infra
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m