---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-todolist-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: dev-project
  source:
    repoURL: http://<HOST(SVC|FQDN|etc..)>/<REPOGIT>.git
    targetRevision: <TARGET_REVISION>
    path: manifests/todolist/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m