expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    ports:
      http:
        nodePort: 30080
externalURL: "http://172.18.0.2:30080"
trivy:
  enabled: false
clair:
  enabled: false
notary:
  enabled: false
exporter:
  enabled: false
